---
- name: Install Docker
  hosts: nodes
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: Set docker architecture variable
      set_fact:
        docker_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'arm64' else 'amd64' }}"
        
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch={{ docker_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: Configure Docker Daemon
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
      notify: Restart Docker


    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
