---
- name: Install Kubernetes
  hosts: nodes
  become: true
  tasks:
    - name: Swap off and remove swap entry
      block:
        - name: Turn off swap
          command: swapoff -a

        - name: Remove swap entry from fstab
          lineinfile:
            path: /etc/fstab
            regexp: '/swap.img'
            state: absent

    - name: Deploy module-conf file
      template:
        src: k8s-module.j2
        dest: /etc/modules-load.d/k8s.conf

    - name: Deploy sysctl-conf file
      template:
        src: k8s-sysctl.j2
        dest: /etc/sysctl.d/k8s.conf

    - name: Configure network settings
      block:
        - name: Load kernel modules for Kubernetes
          modprobe:
            name: "{{ item }}"
          loop:
            - overlay
            - br_netfilter
        - name: Apply sysctl settings
          command: sysctl --system

    - name: Configure containerd
      block:
        - name: Ensure containerd config directory exists
          file:
            path: /etc/containerd
            state: directory

        - name: Create containerd default config
          command: containerd config default
          register: containerd_config

        - name: Set containerd config
          copy:
            content: "{{ containerd_config.stdout }}"
            dest: /etc/containerd/config.toml

        - name: Update containerd config to use systemd cgroup
          command: sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml
        
        - name: Restart containerd service
          service:
            name: containerd
            state: restarted

    - name: Install Kubernetes
      block:
        - name: Add Kubernetes apt key
          apt_key:
            url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
            state: present
            keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

        - name: Add Kubernetes repository
          apt_repository:
            repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
            state: present

        - name: Update apt cache
          apt:
            update_cache: yes

        - name: Install Kubernetes packages
          apt:
            name:
              - kubelet
              - kubeadm
              - kubectl
            state: present
            update_cache: yes

        - name: Hold Kubernetes packages
          apt:
            name:
              - kubelet
              - kubeadm
              - kubectl
            state: fixed

    - name: Configure kubectl bash completion
      shell: kubectl completion bash | tee /etc/bash_completion.d/kubectl

    - name: Reload bash
      shell: /bin/bash -c "source ~/.bashrc"
