---
- name: install DB
  hosts: control
  become: yes
  tasks:
    - name: apply machbase.yaml
      command: kubectl apply -f machbase-neo.yaml
      args:
        chdir: "{{ playbook_dir }}/machbase"
